#!/usr/bin/python3
from dlscript import write_status
import youtube_dl
import os
import glob
import json
import logging
import zipfile

#file name is so this isnt executed as cgi

def print_headers():
    print("Cache-Control: no-cache");
    print("Content-Type: text/event-stream");

def hook(entries):
    if entries['status'] == 'finished':
        write_status("Converting")
    elif entries['status'] == 'downloading':
        filename = entries['tmpfilename'][12:]
        eta = entries['eta']
        eta_str = ' (eta ' + str(eta) + 's)'
        write_status("Downloading " + filename + eta_str)
    elif entries['status'] == 'error':
        write_status("Failed")

def clear_downloads():
    files = glob.glob('downloads/*')
    for f in files:
        os.remove(f)

if __name__ == "__main__":
    logging.basicConfig(filename='log.log', level=logging.DEBUG)

    with open('ydl.json', 'r') as fp:
        ydl_opts = json.load(fp)
    url = ydl_opts['url']
    del ydl_opts['url']
    ydl_opts['progress_hooks'] = [hook]

    with youtube_dl.YoutubeDL(ydl_opts) as ydl:
        try:
            clear_downloads()
            ydl.download([url])
            path = glob.glob('downloads/*')
            if len(path) > 1:
                outpath = ".".join(path[0].split(".")[:-1]) + ".zip"
                with zipfile.ZipFile(outpath, 'w') as zipf:
                    for x in path:
                        zipf.write(x,arcname=x[12:])
                path = outpath
            else:
                path = path[0]

            write_status("Completed",[("url",path)])
        except Exception as e:
            logging.exception(e)
            write_status("Failed")
    os.remove('ydl.json')
